version: 2
updates:

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*adevinta*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
